services:
    _defaults:
        autowire: true
        autoconfigure: true

    Softleister\ContaoPdfGatewayBundle\:
        resource: ../src/
        exclude: ../src/{ContaoManager,DependencyInjection}

    Softleister\ContaoPdfGatewayBundle\Gateway\ContaoPdfGatewayGateway:
        public: true
        tags:
            - { name: 'contao.notification_center.gateway', gateway: 'pdfgateway' }
